name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build # Assuming you have a build script in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # This should match the output directory in next.config.ts
          publish_branch: gh-pages # Or a different branch for deployment